#!/bin/bash

sudo yum -y install git python3-pip openvpn bind iptables
sudo pip install yq

sleep 1 
git clone https://github.com/fauzigo/easyOpenVPN.git
cd easyOpenVPN
sed -i 's/nobody/ec2-user/' vars.yaml
sed -i 's/nogroup/ec2-user/' vars.yaml
sudo ./easyOpenVPN.sh -i
echo 1 |sudo tee /proc/sys/net/ipv4/ip_forward
sudo iptables -t nat -I POSTROUTING -o ens5 -j MASQUERADE
sudo ./easyOpenVPN.sh -c a1
sudo tar cvf /home/ec2-user/a1.tar /etc/openvpn/a1/*

sleep 1

cat > /etc/named.conf <<EOF
options {
	listen-on port 53 { any; };
	listen-on-v6 port 53 { ::1; };
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	secroots-file	"/var/named/data/named.secroots";
	recursing-file	"/var/named/data/named.recursing";
	allow-query     { localhost; 10.8.0.0/24; };

	/*
	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
	 - If you are building a RECURSIVE (caching) DNS server, you need to enable
	   recursion.
	 - If your recursive DNS server has a public IP address, you MUST enable access
	   control to limit queries to your legitimate users. Failing to do so will
	   cause your server to become part of large scale DNS amplification
	   attacks. Implementing BCP38 within your network would greatly
	   reduce such attack surface
	*/
	recursion yes;

	dnssec-validation yes;

	forwarders { 84.200.69.80; 84.200.70.40; };

	forward only;

	managed-keys-directory "/var/named/dynamic";
	geoip-directory "/usr/share/GeoIP";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";

	/* https://fedoraproject.org/wiki/Changes/CryptoPolicy */
	include "/etc/crypto-policies/back-ends/bind.config";
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

zone "." IN {
	type hint;
	file "named.ca";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
EOF

systemctl restart named

echo "SUCCESS"
